import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Passkey from '@/app/_assets/Passkey.jpg';
import "./globals.css";
import Navbar from "@/app/_component/Navbar";
import Footer from "@/app/_component/Footer";
import { Toaster } from "sonner";
import AuthToast from "@/app/_component/AuthToast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Passkey | Password Management App",
  description: "Generated by create next app",
  icons: {
    icon: Passkey.src,
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <AuthToast />
        <Toaster position="top-right" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
